### ISSUE TITLE
Air blocks are not preserved when jumping. 

### ISSUE THREAD

**Issue by falsechicken** [thomasrudin-mt/jumpdrive#1]
It seems as though if you jump inside of something (In my case underground) all the empty air fills with whatever you jumped into? Inside my ship was completely dark and I was wondering why until I realized I was inside of a node xD.

**Comment by thomasrudin** [comment]
That was an optimization for air/ignore skipping, i disabled it for now. There should be a solid logic in the future for moving nodes from/to air/vacuum/ignore
