### ISSUE TITLE
Make Books RE-Writable

### ISSUE THREAD

**Issue by MilesBDyson** [thomasrudin-mt/jumpdrive#48]
it would be nice to re-write books..  when moving around it would be nice to have a book that is the last location i was mining in. i edit the book manually to do this now.. that or make it easy to copy and past the location into a jump drive book already written to... 

maybe a confirmation (are you sure?) when overwriting

**Comment by thomasrudin** [comment]
How about a recipe to renew a book: https://github.com/pandorabox-io/pandorabox_custom/commit/85305a6340602b0023413a89005c94a4ac5163de

**Comment by MilesBDyson** [comment]
perfect ..

**Comment by thomasrudin** [comment]
:+1:
