### ISSUE TITLE
Add compat for pipweorks:teleport_tube

### ISSUE THREAD

**Issue by thomasrudin** [thomasrudin-mt/jumpdrive#9]
Invoke on_destruct() before and on_receive_fields() after jump

### Links
https://gitlab.com/VanessaE/pipeworks/blob/master/teleport_tube.lua

**Comment by SwissalpS** [comment]
It's driving me nuts. After each jump I need to remove and replace not only the jumped tubes but also static tubes. And still sometimes the transfer partially fails. Some items go through, others go to the last destination and the third part just drops about 1 node from the sending tube.

**Comment by thomasrudin** [comment]
> but also static tubes

This should work IMO, how does your setup look like?
Screenshot / coords?

**Comment by SwissalpS** [comment]
Jumpdrive with quarry.  On top of quarry is tp-tube to sorting tube in same jd-volume.
From sorting tube tp-tube to stationary chest at my base.
I need to rename each of these tp-tubes after every jump to have them working properly.
